# --- !Ups

create table "account" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "email" varchar not null,
  "password" varchar not null,
  "city" varchar not null,
  "category" varchar not null
);

# --- !Downs

drop table "people" if exists;