# --- !Ups

create table "account" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "email" varchar not null,
  "password" int not null,
  "city" int not null,
  "category" int not null
);

# --- !Downs

drop table "people" if exists;